#!/usr/bin/env bash

set -e

FIRSTUSER=`getent passwd 1000 | cut -d: -f1`
FIRSTUSERHOME=`getent passwd 1000 | cut -d: -f6`

CURRENT=`grep User= /etc/systemd/system/octoprint.service | cut -d= -f2`

if [ "$CURRENT" = "pi" -a "$FIRSTUSER" != "pi" ]; then
    # if we get here it means that the first user was renamed but we haven't yet
    # updated all of OctoPi's files that depend on that name, so let's do that now

    # fix OctoPrint service file
    echo "Fixing service file"
    sed -i "s!User=pi!User=$FIRSTUSER!g" /etc/systemd/system/octoprint.service
    sed -i "s!ExecStart=/home/pi/!ExecStart=$FIRSTUSERHOME/!g" /etc/systemd/system/octoprint.service
    systemctl daemon-reload

    # fix sudoers files
    echo "Fixing sudoers"
    sed -i "s!^pi!$FIRSTUSER!g" /etc/sudoers.d/octoprint-service
    sed -i "s!^pi!$FIRSTUSER!g" /etc/sudoers.d/octoprint-shutdown

    # fix scripts
    echo "Fixing scripts"
    sed -i "s!/home/pi/!$FIRSTUSERHOME/!g" $FIRSTUSERHOME/scripts/add-octoprint-checkout
    sed -i "s!/home/pi/!$FIRSTUSERHOME/!g" $FIRSTUSERHOME/scripts/welcome
    sed -i "s!/home/pi/!$FIRSTUSERHOME/!g" $FIRSTUSERHOME/.bashrc
    sed -i "s!/home/pi/!$FIRSTUSERHOME/!g" /root/bin/webcamd

    # fix virtualenv
    echo "Fixing paths in virtual environment"
    cd $FIRSTUSERHOME/oprint
    sudo -u $FIRSTUSER $FIRSTUSERHOME/.local/bin/virtualenv-tools --update-path $FIRSTUSERHOME/oprint

    # finally, reboot for all of this to actually take affect
    echo "Adjusted scripts to new user, restarting services..."
    reboot
fi
